<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE playlist [
    <!ELEMENT playlist (song+)>
    <!ELEMENT song (titel, komponist+, interpret*, genre*)>
    <!ELEMENT titel (#PCDATA)>
    <!ELEMENT komponist (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT interpret (#PCDATA)>
    ]>

<playlist>
    <song>
        <titel>
            Bluemoon
        </titel>
        <komponist>
            Richard Rodgers
        </komponist>
        <interpret>
            Ella Fitzgerald
        </interpret>
        <genre>
            Jazz
        </genre>
    </song>
    <song>
        <titel></titel>
    </song>
</playlist>
